jobs:
  build:
    if: startsWith(github.repository,'odpi/')
    name: Verify PR v4
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.0
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: 'build

          --scan

          '
        cache-read-only: true
    - continue-on-error: true
      name: Upload Test coverage report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Jacoco Coverage Report
        path: build/reports/jacoco/codeCoverageReport
    - continue-on-error: true
      name: Upload Log of any dependency failures
      uses: actions/upload-artifact@v4.3.1
      with:
        if-no-files-found: ignore
        name: Dependency Analysis Report (on failure)
        path: build/reports/dependency-analysis/build-health-report.txt
name: Verify PR v4
on:
  repository_dispatch:
    types: trigger-ga___pr-v4.yml
permissions:
  contents: read
