jobs:
  stale:
    if: startsWith(github.repository,'odpi/')
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: startsWith(github.repository,'odpi/')
      name: check stale issues and prs
      uses: actions/stale@v9
      with:
        days-before-close: 20
        days-before-stale: 60
        exempt-issue-labels: pinned
        exempt-pr-labels: pinned
        operations-per-run: 30
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: no-issue-activity
        stale-issue-message: 'This issue has been automatically marked as stale because
          it has not had recent activity. It will be closed in 20 days if no further
          activity occurs. Thank you for your contributions.

          '
        stale-pr-label: no-pr-activity
        stale-pr-message: 'This PR has been automatically marked as stale because
          it has not had recent activity. It will be closed in 20 days if no further
          activity occurs. Thank you for your contributions.

          '
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
